import { createApp } from 'vue';
import { createStore } from 'vuex';
import Antd from 'ant-design-vue';
import moment from 'moment';
import App from './App.vue';
import router from './router';
import '@fontsource/noto-sans-kr';
import '@fontsource/noto-sans-kr/100.css';
import '@fontsource/noto-sans-kr/300.css';
import '@fontsource/noto-sans-kr/400.css';
import '@fontsource/noto-sans-kr/500.css';
import '@fontsource/noto-sans-kr/700.css';
import '@fontsource/noto-sans-kr/900.css';

import './assets/styles/style.css';
import './assets/styles/reset.css';

import 'moment/locale/ko';
import seed from './persistence/seed';

moment.locale('ko');

const app = createApp(App).use(Antd);

const store = createStore({
  mutations: {
    saveLocal(state) {
      localStorage.setItem('state', JSON.stringify(state));
    },
  },
  state() {
    return {
      openedProductionList: [],
      productionList: [
        {
          name: '찰나',
          imgSrc: '/assets/production/chalna.png',
          isLiked: true,
          auditionList: [
            {
              title: '대박나는 작품',
              role: '2',
              ageRange: [30, 40],
              productionName: '파인드 액터',
              prefer: 'F',
              isScrap: true,
              dueDate: '2023-01-27',
              isOffered: true,
              genre: 'ad',
              gender: '2',
              applicantCnt: 0,
              yesCnt: 1,
              noCnt: 1,
            },
          ],
        },
        {
          name: '엑셀시오르콘텐츠랩',
          imgSrc: '/assets/production/profile.jpg',
          isLiked: true,
          auditionList: [
            {
              title: '치명적인 매력남입니다.',
              role: '1',
              ageRange: [27, 29],
              productionName: '파인드 액터',
              prefer: 'F',
              isScrap: true,
              dueDate: '2023-01-27',
              isOffered: true,
              genre: 'movie',
              gender: '1',
              applicantCnt: 0,
              yesCnt: 1,
              noCnt: 1,
            },
          ],
        },
        {
          name: 'IHQ',
          imgSrc: '/assets/production/IHQ.png',
          isLiked: true,
          auditionList: [],
        },
        {
          name: '카카오M',
          imgSrc: '/assets/production/KAKAOM.jpg',
          isLiked: true,
          auditionList: [],
        },
      ],
      audition: {},
      auditionList: [
        {
          id: 101,
          title: '치명적인 매력남입니다.',
          role: '1',
          ageRange: [27, 29],
          heightRange: [175, 181],
          productionName: '숭실대학교 영화전공',
          prefer: 'P',
          isScrap: true,
          dueDate: '2023-01-27',
          isOffered: true,
          genre: 'movie',
          gender: '1',
          applicantCnt: 0,
          yesCnt: 1,
          noCnt: 1,
        },
        {
          id: 102,
          title: '마른하늘에 날벼락!',
          role: '1',
          ageRange: [25, 29],
          heightRange: [170, 180],
          productionName: '숭실대학교 영화전공',
          prefer: 'F',
          isScrap: true,
          dueDate: '2023-01-27',
          isOffered: true,
          genre: 'movie',
          gender: '1',
          applicantCnt: 0,
          yesCnt: 1,
          noCnt: 1,
        },
        {
          id: 103,
          title: '필름 36분의 1',
          role: '1',
          ageRange: [30, 30],
          heightRange: [175, 188],
          productionName: '숭실대학교 영화전공',
          prefer: 'P',
          isScrap: true,
          dueDate: '2023-01-28',
          isOffered: true,
          genre: 'movie',
          gender: '1',
          applicantCnt: 0,
          yesCnt: 1,
          noCnt: 1,
        },
        {
          id: 104,
          title: '좋은 소식',
          role: '1',
          ageRange: [23, 29],
          heightRange: [170, 175],
          productionName: '한겨레영화아카데미',
          prefer: 'G1',
          isScrap: true,
          dueDate: '2023-01-28',
          isOffered: true,
          genre: 'movie',
          gender: '1',
          applicantCnt: 0,
          yesCnt: 1,
          noCnt: 1,
        },
        {
          id: 105,
          title: '기업 사내 웹드라마',
          role: '1',
          ageRange: [23, 29],
          heightRange: [165, 170],
          productionName: '보르다르 에이젼시',
          prefer: 'G1',
          isScrap: true,
          dueDate: '2023-01-28',
          isOffered: true,
          genre: 'ott',
          gender: '1',
          applicantCnt: 0,
          yesCnt: 1,
          noCnt: 1,
        },
        {
          id: 106,
          title: '외국인 CF 모델 구인',
          role: '1',
          ageRange: [40, 49],
          heightRange: [180, 200],
          productionName: '중앙대학교',
          prefer: 'A',
          isScrap: true,
          dueDate: '2023-01-28',
          isOffered: true,
          genre: 'ott',
          gender: '2',
          applicantCnt: 0,
          yesCnt: 1,
          noCnt: 1,
        },
        {
          id: 107,
          title: '바이럴 영상',
          role: '1',
          ageRange: [26, 39],
          heightRange: [170, 180],
          productionName: '넷플릭스',
          prefer: '',
          isScrap: true,
          dueDate: '2023-01-30',
          isOffered: true,
          genre: 'ott',
          gender: '2',
          applicantCnt: 0,
          yesCnt: 1,
          noCnt: 1,
        },
        {
          id: 108,
          title: 'KBS 드라마 주연급 아역',
          role: '1',
          ageRange: [15, 16],
          heightRange: [130, 150],
          productionName: 'KBS',
          prefer: '',
          isScrap: true,
          dueDate: '2023-01-31',
          isOffered: true,
          genre: 'ott',
          gender: '2',
          applicantCnt: 0,
          yesCnt: 1,
          noCnt: 1,
        },

        {
          id: 109,
          title: '<그리우며>',
          role: '1',
          ageRange: [30, 44],
          heightRange: [170, 180],
          productionName: '동국대학교 영상대학원 /홍익대학교 문화예술경영학과',
          prefer: '',
          isScrap: true,
          dueDate: '2023-02-01',
          isOffered: true,
          genre: 'movie',
          gender: '2',
          applicantCnt: 0,
          yesCnt: 1,
          noCnt: 1,
        },
        {
          id: 110,
          title: '<그라데이션>',
          role: '2',
          ageRange: [20, 39],
          heightRange: [160, 180],
          productionName: '동국대학교',
          prefer: '',
          isScrap: true,
          dueDate: '2023-02-01',
          isOffered: true,
          genre: 'movie',
          gender: '1',
          applicantCnt: 0,
          yesCnt: 1,
          noCnt: 1,
        },
        {
          id: 111,
          title: '사랑법',
          role: '1',
          ageRange: [30, 44],
          heightRange: [160, 180],
          productionName: '빅스톤스튜디오, 메리크리스마스',
          prefer: '',
          isScrap: true,
          dueDate: '2023-02-01',
          isOffered: true,
          genre: 'ott',
          gender: '1',
          applicantCnt: 0,
          yesCnt: 1,
          noCnt: 1,
        },
        {
          id: 112,
          title: '<(가제) 눈사람>',
          role: '2',
          ageRange: [20, 60],
          heightRange: [160, 180],
          productionName: '호등타',
          prefer: '',
          isScrap: true,
          dueDate: '2023-02-01',
          isOffered: true,
          genre: 'movie',
          gender: '1',
          applicantCnt: 0,
          yesCnt: 1,
          noCnt: 1,
        },
      ],
      profile: {
        name: '이승찬',
        email: 'zoonyfil@nate.com',
        age: 29,
        height: 176,
        weight: 72,
        genre: 'ott',
        gender: '1',
        tags: ['P', 'F', 'Q'],
        movieList: [
          {
            title: '강철비2: 정상회담',
            url: 'assets/movie/movie1.png',
            imgSrc: '/assets/movie/movie1.jpg',
            role: '백두호 조타사 역',
            year: '2020',
          },
          {
            title: '가장 보통의 연애',
            url: 'assets/movie/movie1.png',
            imgSrc: '/assets/movie/movie2.jpg',
            role: '단역 이자카야 매니저',
            year: '2019',
          },
          {
            title: '마약왕',
            url: 'assets/movie/movie1.png',
            imgSrc: '/assets/movie/movie3.jpg',
            role: '단역-다방 앞 의원 의사역',
            year: '2018',
          },
          {
            title: '밤의 문이 열린다',
            url: 'assets/movie/movie1.png',
            imgSrc: '/assets/movie/movie4.jpg',
            role: '조연 - 이민성 역',
            year: '2019',
          },
        ],
      },
      production: {
        detail: {
          name: '(주)엑셀시오르콘텐츠랩',
          movieList: [
            {
              title: '좋아서만든영화',
              url: 'assets/movie/movie1.png',
              imgSrc: '/assets/production/detail/movie1.jpg',
              role: '',
              year: '2009',
            },
          ],
          auditionList: [
            {
              title: '반드시 너와 함께',
              role: '2',
              ageRange: [30, 40],
              productionName: '파인드 액터',
              prefer: 'F',
              isScrap: true,
              startDate: '2022-12-05',
              endDate: '2023-01-16',
              dueDate: '2023-01-30',
              isOffered: true,
              genre: 'ott',
              gender: '1',
              applicantCnt: 16,
              yesCnt: 11,
              noCnt: 5,
            },
          ],
        },
        findActorList: [
          {
            name: '최창환',
            gender: 'male',
            age: '36',
            height: '178',
            weight: '65',
            imgSrc: '/assets/findActor/1.jpg',
          },
          {
            name: '서정하',
            gender: 'male',
            age: '40',
            height: '171',
            weight: '67',
            imgSrc: '/assets/findActor/2.jpg',
          },
          {
            name: '변상윤',
            gender: 'male',
            age: '30',
            height: '177',
            weight: '65',
            imgSrc: '/assets/findActor/3.jpg',
          },
          {
            name: '남예원',
            gender: 'female',
            age: '24',
            height: '169',
            weight: '55',
            imgSrc: '/assets/findActor/4.jpg',
          },
          {
            name: '이지은',
            gender: 'female',
            age: '25',
            height: '162',
            weight: '46',
            imgSrc: '/assets/findActor/5.jpg',
          },
          {
            name: '전지혜',
            gender: 'female',
            age: '29',
            height: '163',
            weight: '47',
            imgSrc: '/assets/findActor/6.jpg',
          },
          {
            name: '이승찬',
            gender: 'male',
            age: '29',
            height: '176',
            weight: '72',
            imgSrc: '/assets/findActor/7.jpg',
          },
          {
            name: '박건규',
            gender: 'male',
            age: '27',
            height: '171',
            weight: '58',
            imgSrc: '/assets/findActor/8.jpg',
          },
          {
            name: '유홍열',
            gender: 'male',
            age: '34',
            height: '181',
            weight: '67',
            imgSrc: '/assets/findActor/9.jpg',
          },
          {
            name: '강성철',
            gender: 'male',
            age: '28',
            height: '180',
            weight: '75',
            imgSrc: '/assets/findActor/10.jpg',
          },
          {
            name: '이정원',
            gender: 'female',
            age: '22',
            height: '171',
            weight: '48',
            imgSrc: '/assets/findActor/11.jpg',
          },
          {
            name: '이보라',
            gender: 'female',
            age: '24',
            height: '163',
            weight: '46',
            imgSrc: '/assets/findActor/12.jpg',
          },
          {
            name: '이정욱',
            gender: 'male',
            age: '19',
            height: '174',
            weight: '57',
            imgSrc: '/assets/findActor/13.jpg',
          },
          {
            name: '장지영',
            gender: 'female',
            age: '24',
            height: '163',
            weight: '47',
            imgSrc: '/assets/findActor/14.jpg',
          },
          {
            name: '정동철',
            gender: 'male',
            age: '29',
            height: '180',
            weight: '75',
            imgSrc: '/assets/findActor/15.jpg',
          },
          {
            name: '김지선',
            gender: 'female',
            age: '26',
            height: '161',
            weight: '44',
            imgSrc: '/assets/findActor/16.jpg',
          },
          {
            name: '김서정',
            gender: 'female',
            age: '28',
            height: '167',
            weight: '49',
            imgSrc: '/assets/findActor/17.jpg',
          },
          {
            name: '김준희',
            gender: 'male',
            age: '32',
            height: '174',
            weight: '57',
            imgSrc: '/assets/findActor/18.jpg',
          },
          {
            name: '김기덕',
            gender: 'male',
            age: '33',
            height: '181',
            weight: '67',
            imgSrc: '/assets/findActor/19.jpg',
          },
          {
            name: '이보영',
            gender: 'female',
            age: '34',
            height: '163',
            weight: '48',
            imgSrc: '/assets/findActor/20.jpg',
          },
        ],
        applicantList: [],
      },

      count: 0,
    };
  },
});

seed();

app.use(router);
app.use(store);

app.mount('#app');
